#!/usr/bin/python

# makeitso
# Created: 1/1/15
# makeitso is a lightweight deployment tool configured with yaml
# This is the unprivileged utility,
# intended to be run from a standard user account
# Provided you have sudo setup correctly,
# it will pass on details to the privileged utility

import subprocess
import sys
import pwd
import os
import re
from mis_utils import logunit, arg_parser

args = arg_parser()
mislog = logunit(args.quiet, args.verbose, args.logfile)
mislog.log('info', 'Started run')

privargs = ["/usr/bin/sudo", "-u", "makeitso", "/usr/sbin/makeitso-priv"]

# TO DO: Have the priv utility determine who made the sudo call automatically
# privargs.append('-u')
# privargs.append(args.user)

# We can probably do this better too
for i in sys.argv:
    if not re.search('makeitso', i):
        privargs.append(i)

mislog.log('debug', 'Calling makeitso-priv with: '+str(privargs))

try:
    returncode = subprocess.call(privargs)
except:
    logger(args, 'critical', 'Call Failed to makeitso-priv')

mislog.log('info', 'Finished run')
